### ISSUE TITLE
Perte de référencement dossiers/disques après éjection des disques

### ISSUE THREAD

**Issue by CHdeBo** [doodz/Doods.Xam.MonitorMyServer#101]
Bonjour, j'ai remarqué que des disques chauffaient alors que j'étais au travail, alors j'ai éjecté des disques depuis l'application sur mon serveur OMV5 depuis un smartphone Mi 6.

Suite à cela mes dossiers partagés n'étaient plus liés aux périphériques. 
J'ai pu supprimer et remettre les choses en ordre à l'exception d'un dossier qu'il m'est impossible de supprimer.

Son périphérique qui devrait être "DD03" comme je l'ai nommé est "n/a", son chemin relatif est le même que son chemin absolu "/Nas_Home_Utilisateur" qui est le nom du dossier en question, à la place de "/srv/dev-disk..."
Il est marqué comme étant référencé et bien que je l'ai supprimé dans samba ainsi que dans Rsync, il reste "Référencé". Je ne peux donc pas le supprimer définitivement depuis l'onglet "dossier partagé". De plus comme il n'est plus lié à un disque, il ne sert à rien de formater. 

J'ai essayé de le trouver en tant que root, mais sans succès. 

Lorsque je veux modifier le dossier partagé j'ai l'erreur suivante: 

Erreur #0:
OMV\Config\DatabaseException: Failed to execute XPath query '//system/fstab/mntent[uuid='358472d1-3c49-4d2f-bdc9-fd04b03991f8']'. in /usr/share/php/openmediavault/config/database.inc:78
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(234): OMV\Config\Database->get('conf.system.fil...', '358472d1-3c49-4...')
#1 [internal function]: Engined\Rpc\ShareMgmt->get(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('get', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ShareMgmt', 'get', Array, Array, 1)
#5 {main}

Lorsque je veux ajouter le dossier sous samba j'ai bien son nom mais il n'y a pas le disque auquel il est associé entre crochet à coté. Lorsque j'applique j'ai l'erreur suivante:

Erreur #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color samba 2>&1' with exit code '1': debian:
----------
          ID: configure_samba_global
    Function: file.managed
        Name: /etc/samba/smb.conf
      Result: True
     Comment: File /etc/samba/smb.conf updated
     Started: 20:29:49.848533
    Duration: 108.015 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -36,264 +36,3 @@
                   multicast dns register = no
                   # Special configuration for Apple's Time Machine
                   fruit:aapl = yes
                  -#======================= Share Definitions =======================
                  -[Sauvegarde]
                  -path = /srv/dev-disk-by-uuid-444f31b0-f1f6-47e7-9aff-78e1169e06e4/Sauvegarde/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[AnimePlex]
                  -path = /srv/dev-disk-by-uuid-9a4e630a-71ec-4b8f-a990-35ea023961a4/Series&Animes/Series_Animes/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Autres_Videos]
                  -path = /srv/dev-disk-by-uuid-e7adee83-8c0f-4ad7-85ff-2e7db2075285/Plex/Autres_videos/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Config]
                  -path = /srv/dev-disk-by-uuid-e7adee83-8c0f-4ad7-85ff-2e7db2075285/Plex/Config/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Films]
                  -path = /srv/dev-disk-by-uuid-e7adee83-8c0f-4ad7-85ff-2e7db2075285/Plex/Films/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Formations]
                  -path = /srv/dev-disk-by-uuid-e7adee83-8c0f-4ad7-85ff-2e7db2075285/Plex/Formations/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Plex]
                  -path = /srv/dev-disk-by-uuid-e7adee83-8c0f-4ad7-85ff-2e7db2075285/Plex/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[SauvegardeDD01]
                  -path = /srv/dev-disk-by-uuid-997d9629-908c-41f1-a086-5ae395363834/SauvegardeDD01/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[SauvegardeDD05]
                  -path = /srv/dev-disk-by-uuid-cdbca368-277d-4277-841d-887443878c6a/SauvegardeDD05/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Series&Animes]
                  -path = /srv/dev-disk-by-uuid-9a4e630a-71ec-4b8f-a990-35ea023961a4/Series&Animes/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[SeriesPlex]
                  -path = /srv/dev-disk-by-uuid-9a4e630a-71ec-4b8f-a990-35ea023961a4/Series&Animes/Series/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Theatre]
                  -path = /srv/dev-disk-by-uuid-e7adee83-8c0f-4ad7-85ff-2e7db2075285/Plex/Theatre/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
                  -[Nas_Home]
                  -path = /srv/dev-disk-by-uuid-ea4f155b-35fb-42b2-97cc-bd9832fdc839/Nas_Home_Utilisateurs/
                  -guest ok = yes
                  -guest only = yes
                  -read only = no
                  -browseable = yes
                  -inherit acls = yes
                  -inherit permissions = no
                  -ea support = no
                  -store dos attributes = no
                  -vfs objects =
                  -printable = no
                  -create mask = 0664
                  -force create mode = 0664
                  -directory mask = 0775
                  -force directory mode = 0775
                  -hide special files = yes
                  -follow symlinks = yes
                  -hide dot files = yes
                  -
----------
          ID: configure_samba_shares
    Function: file.append
        Name: /etc/samba/smb.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 732, in execute
                  self._response = self._response[0]
              IndexError: list index out of range

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
                  return original_render(self, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 33, in top-level template code
                File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 438, in call
                  return __context.call(__obj, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 100, in get_sharedfolder_path
                  mp_obj = get('conf.system.filesystem.mountpoint', sf_obj['mntentref'])
                File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
                  objs = db.get(id_, identifier)
                File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
                  query.execute()
                File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 737, in execute
                  raise DatabaseQueryNotFoundException(self.xpath, self.model)
              openmediavault.config.database.DatabaseQueryNotFoundException: No such object: //system/fstab/mntent[uuid='358472d1-3c49-4d2f-bdc9-fd04b03991f8']

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2172, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2316, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 6162, in append
                  source_list=sl_, template=template, defaults=defaults, context=context
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 1124, in _get_template_texts
                  source, "", template=template, saltenv=__env__, context=tmpctx, **kwargs
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/cp.py", line 318, in get_template
                  return _client().get_template(path, dest, template, makedirs, saltenv, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 806, in get_template
                  data = salt.utils.templates.TEMPLATE_REGISTRY[template](sfn, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 261, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 543, in render_jinja_tmpl
                  "Jinja error: {}{}".format(exc, out), line, tmplstr, trace=tracestr
              salt.exceptions.SaltRenderError: Jinja error: No such object: //system/fstab/mntent[uuid='358472d1-3c49-4d2f-bdc9-fd04b03991f8']
              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 732, in execute
                  self._response = self._response[0]
              IndexError: list index out of range

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
                  return original_render(self, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 33, in top-level template code
                File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 438, in call
                  return __context.call(__obj, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 100, in get_sharedfolder_path
                  mp_obj = get('conf.system.filesystem.mountpoint', sf_obj['mntentref'])
                File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
                  objs = db.get(id_, identifier)
                File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
                  query.execute()
                File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 737, in execute
                  raise DatabaseQueryNotFoundException(self.xpath, self.model)
              openmediavault.config.database.DatabaseQueryNotFoundException: No such object: //system/fstab/mntent[uuid='358472d1-3c49-4d2f-bdc9-fd04b03991f8']

              ; line 33

              ---
              [...]
              {%- for share in config.shares.share | selectattr('enable') %}
              [{{ salt['omv_conf.get_sharedfolder_name'](share.sharedfolderref) }}]
              {%- if share.comment | length > 0 %}
              comment = {{ share.comment }}
              {%- endif %}
              path = {{ salt['omv_conf.get_sharedfolder_path'](share.sharedfolderref) }}    <======================
              guest ok = {% if share.guest != 'no' %}yes{% else %}no{% endif %}
              guest only = {% if share.guest == 'only' %}yes{% else %}no{% endif %}
              read only = {% if share.readonly | to_bool %}yes{% else %}no{% endif %}
              browseable = {% if share.browseable | to_bool %}yes{% else %}no{% endif %}
              inherit acls = {% if share.inheritacls | to_bool %}yes{% else %}no{% endif %}
              [...]
              ---
     Started: 20:29:49.956758
    Duration: 794.729 ms
     Changes:
----------
          ID: configure_samba_recyclebin_cron
    Function: file.managed
        Name: /etc/cron.daily/openmediavault-samba-recycle
      Result: True
     Comment: File /etc/cron.daily/openmediavault-samba-recycle is in the correct state
     Started: 20:29:50.751726
    Duration: 3.014 ms
     Changes:
----------
          ID: remove_samba_recyclebin_cron_scripts
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 20:29:50.755742
    Duration: 3.137 ms
     Changes:
              ----------
              file.find:
----------
          ID: configure_default_wsdd
    Function: file.managed
        Name: /etc/default/wsdd
      Result: True
     Comment: File /etc/default/wsdd is in the correct state
     Started: 20:29:50.759078
    Duration: 2.831 ms
     Changes:
----------
          ID: test_samba_service_config
    Function: cmd.run
        Name: samba-tool testparm --suppress-prompt
      Result: True
     Comment: Command "samba-tool testparm --suppress-prompt" run
     Started: 20:29:50.762956
    Duration: 113.219 ms
     Changes:
              ----------
              pid:
                  30400
              retcode:
                  0
              stderr:
              stdout:
                  # Global parameters
                  [global]
                  	disable spoolss = Yes
                  	encrypt passwords = Yes
                  	guest account = nobody
                  	log file = /var/log/samba/log.%m
                  	logging = syslog
                  	log level = 2
                  	map to guest = Bad User
                  	max log size = 1000
                  	pam password change = Yes
                  	panic action = /usr/share/samba/panic-action %d
                  	passdb backend = tdbsam
                  	passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
                  	passwd program = /usr/bin/passwd %u
                  	printcap name = /dev/null
                  	server string = %h server
                  	socket options = TCP_NODELAY IPTOS_LOWDELAY
                  	unix extensions = Yes
                  	workgroup = WORKGROUP
                  	fruit:aapl = yes
                  	aio read size = 16384
                  	aio write size = 16384
                  	create mask = 0777
                  	directory mask = 0777
                  	use sendfile = Yes
----------
          ID: start_samba_service
    Function: service.running
        Name: smbd
      Result: False
     Comment: One or more requisite failed: omv.deploy.samba.20shares.configure_samba_shares
     Started: 20:29:50.903699
    Duration: 0.01 ms
     Changes:
----------
          ID: start_samba_service_nmbd
    Function: service.running
        Name: nmbd
      Result: False
     Comment: One or more requisite failed: omv.deploy.samba.default.start_samba_service
     Started: 20:29:50.904121
    Duration: 0.004 ms
     Changes:
----------
          ID: start_wsdd_service
    Function: service.running
        Name: wsdd
      Result: True
     Comment: The service wsdd is already running
     Started: 20:29:50.904213
    Duration: 57.984 ms
     Changes:

Summary for debian
------------
Succeeded: 6 (changed=3)
Failed:    3
------------
Total states run:     9
Total run time:   1.083 s in /usr/share/php/openmediavault/system/process.inc:195
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus28...', '/tmp/bgoutputUi...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

Est-ce que c'est un problème connu ? existe t'il une solution ? 
En vous remerciant,
Cordialement,

**Comment by doodz** [comment]
Bonjour CHdeBo,
L’application n’est pas officielle, j’utilise l’api exposé par Openmediavault.
La faut plutôt demander sur le forum officiel ça semble interne a OMV :
https://forum.openmediavault.org/

Franchement j’ai lu et passé du temps sur ton ticket, il semble y a voir un problème au niveau de la base de données. Et pour le fait que ton dossier soit impossible à supprimer, cela vient peut-être là aussi, mais il peut très bien être utilisé aussi par un autre service et/ou utilisateur vu son nom.

Donne moi l’url de ton poste sur le forum je tâcherais de suivre et d’apporter ma contribution si je peux.

doods

-----------------------------------------------------------------------------------------------------------
Hello CHdeBo,
The application is not official, I use the API exposed by Openmediavault.
The need rather ask on the official forum , your problem seems internal to OMV:
https://forum.openmediavault.org/

Frankly I have read and spent time on your ticket, there seems to be a problem with the database. And for the fact that your file is impossible to delete, that may also be there, but it could very well also be used by another service and / or user given its name.

Give me the url of your post on the forum I will try to follow and contribute if I can.
