### ISSUE TITLE
[BUG] Version 110 for Android

### ISSUE THREAD

**Issue by edgd1er** [doodz/Doods.Xam.MonitorMyServer#94]
**Describe the bug**
After having updated the app to version 110, I cannot connect to the OpenMediavault NAS.
I tried to install version 109, I have the same problem. I must say, I didn't run the app recently, so I cannot pinpoint when it occured. I suspect a change in OMV web API as version 109 used to work properly.

**To Reproduce**
1. start the app
2. Click on manage hosts
3. click Find 
4. select OMV web control panel line
5. A mail is received as login was performed
6. the App crashes.

**Expected behavior**
App doesn't crash and display information about the server it is connected to

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus 5
 - OS: Android 10
 - OMV server 5.6.2-1 
 - App Version 110

**Additional context**

Log for Android logReader app:
FATAL EXCEPTION: main
Process: com.doods.monitormyserver, PID: 32510
android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
at android.content.res.ResourcesImpl.getResourceTypeName(ResourcesImpl.java:292)
at android.content.res.Resources.getResourceTypeName(Resources.java:2108)
at androidx.fragment.app.FragmentAnim.loadAnimation(FragmentAnim.java:79)
at androidx.fragment.app.DefaultSpecialEffectsController$AnimationInfo.getAnimation(DefaultSpecialEffectsController.java:774)
at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:144)
at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:120)
at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:294)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2190)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7697)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
--

**Comment by doodz** [comment]
Thanks for the feedback.
Actualy, I am working with resources and maybe I forgot a translation for a specific language.
Can you tell me the language of your system?
In fact, I can't try anything. Updating my compiler broke my version: /.
I wait for a fix

**Comment by edgd1er** [comment]
Hi,

My language is French.
